### ISSUE TITLE
Version 1.1.0 throws 'Call to a member function getElementsByTagName()", version 1.0.8 does not

### ISSUE THREAD

**Issue by mig5** [hallowelt/migrate-confluence#42]
Hi,

Thanks for this really useful tool.

When I use version 1.0.8, I can perform `migrate-confluence analyze --src input/ --dest workspace/` on a Confluence export without errors.

On the same export data, on the same machine (running PHP 7.4, Debian 11), when using version 1.1.0, I get this error:

```
PHP Fatal error:  Uncaught Error: Call to a member function getElementsByTagName() on null in phar:///usr/local/bin/migrate-confluence/src/Utility/XMLHelper.php:65
Stack trace:
#0 phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php(161): HalloWelt\MigrateConfluence\Utility\XMLHelper->getIDNodeValue(NULL)
#1 phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php(131): HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer->makeSpacesMap()
#2 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-migration/src/AnalyzerBase.php(67): HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer->doAnalyze(Object(SplFileInfo))
#3 phar:///usr/local/bin/migrate-confluence/src/Analyzer/ConfluenceAnalyzer.php(115): HalloWelt\MediaWiki\Lib\Migration\AnalyzerBase->analyze(Object(SplFileInfo))
#4 phar:///usr/local/bin/migrate-confluence/vendor/hallowelt/mediawiki-lib-migration/src/Command/Analyze.php(50): HalloWelt\MigrateConfluence\Analyzer\ConfluenceAnalyzer->analyze(Object(SplF in phar:///usr/local/bin/migrate-confluence/src/Utility/XMLHelper.php on line 65
```

Any ideas why the new release causes this issue?

```
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies
```

**Comment by osnard** [comment]
Apparently there are situations where a space has no `homepage` property set. There is now a fix available: https://github.com/hallowelt/migrate-confluence/pull/44

**Comment by osnard** [comment]
Has been merged and should be fixed with release of 1.1.1
